include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    library_private_types_in_public_api: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    void_checks: ignore
