include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    library_private_types_in_public_api: ignore
    must_be_immutable: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_final_fields: ignore
    unused_import: ignore
    use_build_context_synchronously: ignore
    void_checks: ignore
