name: journal_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  get: ^4.6.6
  get_it: ^8.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  cloud_firestore: ^5.4.2
  getwidget: ^4.0.0
  responsive_builder: ^0.7.1
  csc_picker: ^0.2.7
  firebase_auth: ^5.3.0
  flutter_admin_scaffold: ^1.3.0
  file_picker: ^8.1.2
  firebase_storage: ^12.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
